---
- name: Deploy application container
  hosts: docker
  become: true
  tasks:
  - name: Create a reddit container
    docker_container:
      name: "reddit"
      image: "anrad13/otus-reddit:1.0"
      exposed_ports:
        - "9292"
      ports:
        - "9292:9292"
