version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  comment_db:
    image: mongo:3.2
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
  ui:
    #build: ./ui
    image: anrad13/ui:${VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    #build: ./post-py
    image: anrad13/post:${VERSION}
    networks:
      - back_net
      - front_net
  comment:
    #build: ./comment
    image: anrad13/comment:${VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: anrad13/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net
  
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:
  comment_db:
  prometheus_data:

networks:
  back_net:
  front_net:
